-- Dev user database schema (SQLite)
-- User IDs are numeric, starting at 1000000001 (generated by application/script).

-- Users table
CREATE TABLE IF NOT EXISTS users (
    userid          INTEGER PRIMARY KEY CHECK (userid >= 1000000001),
    user_email      TEXT NOT NULL UNIQUE,
    tenant_id       TEXT NOT NULL,
    password_hash   TEXT NOT NULL,   -- base64-encoded hash (e.g. base64(sha256(salt || password)))
    salt            TEXT NOT NULL,   -- random salt stored in base64
    last_login_ts   TEXT,            -- ISO8601 or Unix timestamp; NULL if never logged in
    created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now')),
    updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

-- Index for login lookup by email
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users(user_email);

-- Index for listing/filtering by tenant
CREATE INDEX IF NOT EXISTS idx_users_tenant ON users(tenant_id);

-- Optional: trigger to refresh updated_at on row change (SQLite 3.35+)
-- CREATE TRIGGER users_updated_at AFTER UPDATE ON users
-- BEGIN
--     UPDATE users SET updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE userid = NEW.userid;
-- END;
